[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { path = "../data" }
# enigo = "0.2.1"
mlua = { version = "0.9.9", features = ["lua54", "vendored"] }
sdl2 = "0.37.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.63"
