[package]
name = "scraper-optcg"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { path = "../data" }
html5ever = "0.25.0"
scraper = "0.20.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
thiserror = "1.0.63"
ureq = "2.10.1"
